/// Flutter icons Icons_custom
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons_custom
///      fonts:
///       - asset: fonts/Icons_custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsCustom {
  IconsCustom._();

  static const _kFontFam = 'Icons_custom';

  static const IconData pro = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData basic = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData offlinedevice = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData onlinedevice = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe806, fontFamily: _kFontFam);
}
